### ISSUE TITLE
Can't deploy metrics with wildcard certificate

### ISSUE THREAD

**Issue by gravis** [openshift/origin-metrics#127]
Hi,

I have a wildcard cert, and can't deploy metrics because of the PREFLIGHT check:

```
PREFLIGHT CHECK FAILED
========================
validate_deployer_secret: 
CHECK true
CHECK false
CHECK false
CHECK false
1 2
The supplied hawkular-metrics.pem certificate is required to match the following name(s) in the Subject Alternative Name field:
cluster-metrics.tech-angels.net hawkular-metrics
Instead the certificate has:
*.domain.tld domain.tld
Please supply a correct certificate or omit it to allow the deployer to generate it.

Deployment has been aborted prior to starting, as these failures often indicate fatal problems.
Please evaluate any error messages above and determine how they can be addressed.
To ignore this validation failure and continue, specify IGNORE_PREFLIGHT=true.

PREFLIGHT CHECK FAILED
```

Specifying IGNORE_PREFLIGHT in the template has no effect.

Openshift 1.2.0
Image: openshift/origin-metrics-deployer:latest

Thanks

**Comment by mwringe** [comment]
I may be missing something, but shouldn't this certificate fail? Your certificate appears to be valid for "*.domain.tld" does not match "cluster-metrics.tech-angels.net".

The IGNORE_PREFLIGHT not working for you is more serious, I will check into that as to why it is not working.

**Comment by gravis** [comment]
I forgot to redact the hostname :) 
Of course, the cert is *.tech-angels.net

thanks

**Comment by mwringe** [comment]
ah, ok, hmm, I will look into that. I know we have a test which specifically checks for this, so I may have to look into that as well.

What version exactly of the containers are you using?

**Comment by gravis** [comment]
I'm using the latest version, https://hub.docker.com/r/openshift/origin-metrics-deployer/tags/
so the one build 4 days ago. It was failing already before this release.

Thanks

**Comment by mwringe** [comment]
Ok, I can reproduce the issue with IGNORE_PREFLIGHT not working and I will have a fix and test added soon. A new latest image should be soon coming out with the fix.

Are you sure your wildcard certificate is valid for 'hawkular-metrics'. The certificate must be valid for the internal hostname as well as the external one. But this requirement is going away very soon (most likely in the next couple of hours) as we are changing from a passthrough route to a re-encrypting one (see https://github.com/openshift/origin-metrics/pull/121)

**Comment by gravis** [comment]
Great!
Thanks

**Comment by mwringe** [comment]
Can you try now with the latest docker image? only the deployer got updated.

I will let you know when the other commit gets in for the re-encrypting route stuff.

**Comment by gravis** [comment]
```
Creating the Cassandra Certificate Secrets configuration json file
++ base64 -w 0 /etc/deploy/_output/hawkular-cassandra.cert
++ base64 -w 0 /etc/deploy/_output/hawkular-cassandra-ca.cert
+ echo 'Creating Hawkular Metrics & Cassandra Secrets'
+ oc create -f /etc/deploy/_output/hawkular-metrics-secrets.json
Creating Hawkular Metrics & Cassandra Secrets
Error from server: error when creating "/etc/deploy/_output/hawkular-metrics-secrets.json": secrets "hawkular-metrics-secrets" already exists
```
The redeploy is apparently missing things. Btw `redeploy` is broken for me too, it's just a `cleanup`: it removes everything and exit.

**Comment by mwringe** [comment]
Redeploy should be working. Are you using 'REDEPLOY=true' or 'MODE=redeploy'

**Comment by gravis** [comment]
If I use that, I get an empty project, everything is removed, and nothing recreated :(

**Comment by gravis** [comment]
The deployer pod is never ending, with:

```
========================
--- validate_deployment_artifacts ---
======== RETRY =========
validate_deployment_artifacts: 
Pod hawkular-metrics-gnc3b from ReplicationController hawkular-metrics is running but not marked ready.
This is most often due to either startup latency or crashing for lack of other services.
It should resolve over time; if not, check the pod logs to see what is going wrong.
  * * * * 
Pod heapster-14dlp from ReplicationController heapster is running but not marked ready.
This is most often due to either startup latency or crashing for lack of other services.
It should resolve over time; if not, check the pod logs to see what is going wrong.
  * * * * 
```
(loop).

Heapster is failing with 

```
'https://hawkular-metrics:443/hawkular/metrics/status' is not accessible [HTTP status code: 000. Curl exit code 7]. Retrying.
Endpoint check for 'https://hawkular-metrics:443/hawkular/metrics/status' could not be established after 120 seconds. Aborting
```
(loop)

and hawkular metrics is failing with

```
13:34:09,623 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200002: Initializing metrics service
13:34:09,882 WARN  [io.netty.util.concurrent.DefaultPromise] (cluster44-nio-worker-0) An exception was thrown by com.datastax.driver.core.Connection$10.operationComplete(): java.util.concurrent.RejectedExecutionException: Task com.datastax.driver.core.Connection$10$1@6d717f9e rejected from java.util.concurrent.ThreadPoolExecutor@1b42013[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:550)
	at com.datastax.driver.core.Connection$10.operationComplete(Connection.java:560)
	at com.datastax.driver.core.Connection$10.operationComplete(Connection.java:534)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:262)
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:117)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1281)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:625)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

13:34:09,883 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200003: Could not connect to Cassandra cluster - assuming its not up yet: All host(s) tried for query failed (tried: hawkular-cassandra/172.30.109.221:9042 (com.datastax.driver.core.exceptions.TransportException: [hawkular-cassandra/172.30.109.221] Channel has been closed))
13:34:09,884 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200004: [44] Retrying connecting to Cassandra cluster in [4]s...
13:34:13,884 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200002: Initializing metrics service
13:34:14,149 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200003: Could not connect to Cassandra cluster - assuming its not up yet: All host(s) tried for query failed (tried: hawkular-cassandra/172.30.109.221:9042 (com.datastax.driver.core.exceptions.TransportException: [hawkular-cassandra/172.30.109.221] Channel has been closed))
13:34:14,149 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200004: [45] Retrying connecting to Cassandra cluster in [1]s...
```

**Comment by gravis** [comment]
refs #133 for the redeploy issue

**Comment by gravis** [comment]
I have retried many times, on openshift 1.2.0, and `hawkular-metrics` doesn't start, preventing heapster from starting too:

```
13:34:23,880 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200003: Could not connect to Cassandra cluster - assuming its not up yet: All host(s) tried for query failed (tried: hawkular-cassandra/172.30.213.167:9042 (com.datastax.driver.core.exceptions.TransportException: [hawkular-cassandra/172.30.213.167] Channel has been closed))
13:34:23,880 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200004: [48] Retrying connecting to Cassandra cluster in [4]s...
13:34:23,879 WARN  [io.netty.util.concurrent.DefaultPromise] (cluster48-nio-worker-0) An exception was thrown by com.datastax.driver.core.Connection$10.operationComplete(): java.util.concurrent.RejectedExecutionException: Task com.datastax.driver.core.Connection$10$1@f763ad2 rejected from java.util.concurrent.ThreadPoolExecutor@738b5267[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:550)
	at com.datastax.driver.core.Connection$10.operationComplete(Connection.java:560)
	at com.datastax.driver.core.Connection$10.operationComplete(Connection.java:534)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:262)
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:117)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1281)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:625)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

13:34:24,840 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
*** JBossAS process (121) received TERM signal ***
13:34:24,875 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 65) WFLYUT0022: Unregistered web context: /hawkular/metrics
13:34:24,889 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0019: Host default-host stopping
13:34:24,889 INFO  [org.jboss.weld.deployer] (MSC service thread 1-6) WFLYWELD0010: Stopping weld service for deployment hawkular-metrics-api-jaxrs.war
13:34:24,914 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
13:34:24,921 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-8) WFLYJCA0019: Stopped Driver service with driver-name = h2
13:34:24,925 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTPS listener httpsServer suspending
13:34:24,928 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0008: Undertow HTTP listener default suspending
13:34:24,929 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 0.0.0.0:8080
13:34:24,930 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTPS listener httpsServer stopped, was bound to 0.0.0.0:8443
13:34:24,931 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0004: Undertow 1.3.15.Final stopping
13:34:24,957 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0028: Stopped deployment hawkular-metrics-api-jaxrs.war (runtime-name: hawkular-metrics-api-jaxrs.war) in 112ms
13:34:24,959 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0050: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) stopped in 110ms
*** JBossAS process (121) received TERM signal ***
```

**Comment by gravis** [comment]
Do I have to remove my `metrics-deployer` secret?

**Comment by mwringe** [comment]
What exactly is your setup like? I have not run into these issues.

Heapster will not properly start up until Hawkular Metrics does.

The "java.util.concurrent.RejectedExecutionException" error message is known and benign. You can safely ignore this (see https://github.com/openshift/origin-metrics/blob/master/docs/known_issues.adoc#rejectedexecutionexception-in-hawkular-metrics-logs)

The message in the Hawkular Metrics logs "*** JBossAS process (121) received TERM signal ***" most likely means that something is killing the pod. What is showing up in the event logs?

**Comment by gravis** [comment]
`Liveness probe failed: Hawkular metrics has been running for 147 seconds. Aborting`
That's why it's killed, but that's the conclusion of the pod not starting.
My setup is the one described here: https://docs.openshift.com/enterprise/3.1/install_config/cluster_metrics.html

```
$ oc create -f - <<API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-deployer
secrets:
- name: metrics-deployer
API
```

```
oadm policy add-role-to-user \
    edit system:serviceaccount:openshift-infra:metrics-deployer
```

```
oadm policy add-cluster-role-to-user \
    cluster-reader system:serviceaccount:openshift-infra:heapster
```

```
 oc secrets new metrics-deployer \
    hawkular-metrics.pem=/home/openshift/metrics/hm.pem \
    hawkular-metrics-ca.cert=/home/openshift/metrics/hm-ca.cert
```

and then running the metrics deployer template.

**Comment by mwringe** [comment]
Can you post the full Hawkular Metrics logs?

**Comment by gravis** [comment]
There you go :)
https://gist.github.com/gravis/558a508ddd03d2c74be878798bfc8dbd
thanks!

**Comment by gravis** [comment]
(updated with cassandra + heapster logs)

**Comment by mwringe** [comment]
Hmm, it looks like Hawkular Metrics cannot connect to the Cassandra instance. Is Cassandra and Hawkular Metrics running on separate nodes with a firewall running between them?

The only other thing I could think of would be that Cassandra is not trusting the connection to Hawkular Metrics. This could be happened if you specified a hawkular-metrics.pem and not the hawkular-metrics-ca.cert. The connections to Cassandra are enforced with client certificates.

But, there was a big change yesterday with how certificates are being handled, and you should no longer be encountering this situation.

If you are using origin, can you just pull in the latest openshift/origin-metrics-deployer image?

If you are using OSE, can you please delete your existing secrets for the deployer, create an empty one instead (eg oc secrets new metrics-deployer nothing=/dev/null) to see if that resolves the issue you are seeing?

**Comment by gravis** [comment]
There's a firewall, indeed, I can see the pod are not deployed in same region. But there are sharing a private vlan, so this should not be a problem:

```
-bash-4.2# curl https://172.30.213.167:9042 -Ik
curl: (35) NSS: client certificate not found (nickname not specified)
```
(from the node in the US, to the node in EU)

I'm using origin, but I don't see how could I pull the latest `openshift/origin-metrics-deployer`? It should be pulled automatically when I run the template, right?

I will try without the certs, so removing the `metrics-deployer` secret.
Thanks again for your help

**Comment by gravis** [comment]
yup `pulling image "openshift/origin-metrics-deployer:latest"` it's pulling the latest before each deploy

**Comment by gravis** [comment]
Ok, now it's working. Fun fact, as the same cert was installed on master, it's being used indirectly for our route.
Thanks

**Comment by gravis** [comment]
We're seeing "holes" on pods being in another region, all local nodes are OK. Have you already seen that?

**Comment by mwringe** [comment]
It could be that the connection between the nodes is too slow for the current metrics gathering interval. This is set by default to be 10s in the Heapster template. An easy way to check this would be to edit the Heapster rc and set 'metric_resolution' from '10s' to something like '20s' or '30s'. This can also be specified with the METRICS_RESOLUTION template parameter for the deployer (https://github.com/openshift/origin-metrics/blob/master/metrics.yaml#L141).

The other thing to check is if the time on the servers are using an NTP server.

**Comment by gravis** [comment]
I have bigger holes than that :)
![screenshot 2016-06-02 11 56 59](https://cloud.githubusercontent.com/assets/12752/15751740/2ada9ab4-28b9-11e6-9abf-f335911ec83b.png)
but I'll try to update the METRICS_RESOLUTION to 20s to see where it's going.

thanks!

**Comment by gravis** [comment]
Hmm, that's weird (and not related to this issue), but the holes "disappear" if I change the time range:

![screenshot 2016-06-02 13 01 58](https://cloud.githubusercontent.com/assets/12752/15753667/4b188058-28c2-11e6-8bdb-afd3839ccdef.png)

then
![screenshot 2016-06-02 13 02 50](https://cloud.githubusercontent.com/assets/12752/15753677/5690c68e-28c2-11e6-8e8d-7e078365479b.png)

back to 30 minutes, it's gone:

![screenshot 2016-06-02 13 03 11](https://cloud.githubusercontent.com/assets/12752/15753686/6432d0a2-28c2-11e6-8ab6-ecc299b802cf.png)
