### ISSUE TITLE
Buffer was already freed error

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-metrics#134]
Seeing this stack trace again and again in my environment. Metrics worked fine for a while, but eventually CPU and Network metrics stopped showing up in OpenShift. Memory metrics still work.

```
19:37:37,389 ERROR [org.xnio.listener] (default I/O-5) XNIO001007: A channel event listener threw an exception: java.lang.NullPointerException
19:38:07,393 ERROR [io.undertow.client] (default I/O-3) UT005001: An exception occurred processing the request: java.lang.IllegalStateException: XNIO000017: Buffer was already freed
    at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:213)
    at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:183)
    at org.xnio.ssl.JsseSslConduitEngine.isDataAvailable(JsseSslConduitEngine.java:1187)
    at org.xnio.ssl.JsseSslStreamSourceConduit.read(JsseSslStreamSourceConduit.java:76)
    at org.xnio.conduits.PushBackStreamSourceConduit.read(PushBackStreamSourceConduit.java:52)
    at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
    at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:487)
    at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:472)
    at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
    at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
    at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
    at org.xnio.nio.NioHandle$1.run(NioHandle.java:50)
    at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
    at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)
```

/cc @mwringe

**Comment by mwringe** [comment]
@jsanda @stefannegrea any ideas?

**Comment by mwringe** [comment]
Corresponding jira: https://issues.jboss.org/browse/HWKMETRICS-408

**Comment by tsegismont** [comment]
Looks similar to the issue you had reported @mwringe 
See https://github.com/hawkular/hawkular-metrics/pull/481#issuecomment-214861809

```
19:26:02,172 ERROR [io.undertow.client] (default I/O-6) UT005001: An exception occurred processing the request: java.lang.IllegalStateException: XNIO000017: Buffer was already freed
	at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:213)
	at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:183)
	at org.xnio.ssl.JsseSslConduitEngine.isDataAvailable(JsseSslConduitEngine.java:1187)
	at org.xnio.ssl.JsseSslStreamSourceConduit.read(JsseSslStreamSourceConduit.java:76)
	at org.xnio.conduits.PushBackStreamSourceConduit.read(PushBackStreamSourceConduit.java:52)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:487)
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:472)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.NioHandle$1.run(NioHandle.java:50)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

19:26:02,177 ERROR [org.xnio.listener] (default I/O-6) XNIO001007: A channel event listener threw an exception: java.lang.NullPointerException
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:596)
	at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:472)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.NioHandle$1.run(NioHandle.java:50)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)
```

I'll ask Undertow devs for advice.

**Comment by tsegismont** [comment]
@spadgett Can you confirm if all requests fail or just some of them? Can you check your logs again and tell me if error messages come in pair, from the same thread (default I/O-X)? I'm asking because in your snippet, they seems separated by 30s.

**Comment by spadgett** [comment]
@tsegismont you can probably say better than I can.... I attached the full log to the JIRA here:

https://issues.jboss.org/secure/attachment/12405779/hawkular.log

**Comment by tsegismont** [comment]
Thank you

2016-06-01 17:10 GMT+02:00 Sam Padgett <notifications@github.com>:

**Comment by tsegismont** [comment]
So yes, it looks like the same error reported by Matt before. Will talk
with Undertow guys

2016-06-01 17:25 GMT+02:00 Thomas SEGISMONT <tsegismont@gmail.com>:

**Comment by tsegismont** [comment]
@spadgett I've just sent a PR https://github.com/hawkular/hawkular-metrics/pull/512

We will need you to test the update in the same environment because I'm not able to reproduce locally.
