### ISSUE TITLE
Handle IP Address Changes for Cassandra

### ISSUE THREAD

**Issue by jsanda** [openshift/origin-metrics#323]
We need to handle IP address changes for Cassandra. If Cassandra restarts and the address it uses to listen for gossip changes, then this could trigger the node the bootstrap again and token assignments to get recalculated and possibly changes. This potentially means:

* longer start up
* streaming data that could otherwise be avoided
* nodes holding onto data they no longer own

We need to start Cassandra with ```-Dcassandra.replace_address_first_boot=true``` to let it know that token assignments should not change and to simply update its gossip address.

**Comment by mwringe** [comment]
This parameter appears to only work if we are dealing with existing data. If we run this the first time with a clean Cassandra instance, it will fail with the following error:


Exception (java.lang.RuntimeException) encountered during startup: Replacement ost name could not be resolved or scope_id was specified for a global IPv6 address
java.lang.RuntimeException: Replacement ost name could not be resolved or scope_id was specified for a global IPv6 address
	at org.apache.cassandra.config.DatabaseDescriptor.getReplaceAddress(DatabaseDescriptor.java:1017)
	at org.apache.cassandra.config.DatabaseDescriptor.isReplacing(DatabaseDescriptor.java:1044)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:636)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:572)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:346)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:569)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:697)
Caused by: java.net.UnknownHostException: true: Name or service not known

See the full log here: https://gist.github.com/mwringe/e628007893ad85542a93353789b5ec78

**Comment by jsanda** [comment]
Here's a simple check we can perform. If the data directory for the system.local either does not exists or has no files, then do not start with ```-Dcassandra.replace_address_first_boot=true```. That's where the addresses are stored.
