### ISSUE TITLE
Cassandra dockerfile can't support to build cassandra 3.11.0 from source code

### ISSUE THREAD

**Issue by WangHouLing** [openshift/origin-metrics#372]
##### Version
Cassandra:3.11.0

##### Steps To Reproduce
1. Download openshift/origin-metrics/cassandra directory.
2. Edit Dockerfile:
```
# The Cassandra version
ENV CASSANDRA_VERSION="3.11.0" \
    CASSANDRA_HOME="/opt/apache-cassandra" \
    HOME="/home/cassandra" \
    PATH="/opt/apache-cassandra/bin:$PATH" \
    CASSANDRA_NODES_SERVICE_NAME="hawkular-cassandra-nodes"
```
3. Run `sudo docker build -t test/cassandra:v3.11.0 .` .
##### Current Result

```
  [javadoc]  * <br/>
  [javadoc]    ^
  [javadoc] /tmp/cassandra/src/java/org/apache/cassandra/net/RateBasedBackPressureState.java:43: error: self-closing element not allowed
  [javadoc]  * <br/>
  [javadoc]    ^
  [javadoc] Building index for all the packages and classes...
  [javadoc] Building index for all classes...
  [javadoc] Generating /tmp/cassandra/build/javadoc/help-doc.html...
  [javadoc] 65 errors
  [javadoc] 100 warnings

gen-doc:

BUILD FAILED
/tmp/cassandra/build.xml:260: Execute failed: java.io.IOException: Cannot run program "make" (in directory "/tmp/cassandra/doc"): error=2, No such file or direc
tory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 23 more

Total time: 19 minutes 20 seconds
```
I know `/tmp/cassandra/doc` directory is exits at start and isn't delete in Dockerfile.I am wondering why have this problem.
I just wanted to upgrade the Cassandra version to 3.11.0,please help me.
I will be grateful for any help you can provide.

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
