### ISSUE TITLE
Met "Could not connect to Cassandra cluster" in hawkular-metrics Pod

### ISSUE THREAD

**Issue by chunyunchen** [openshift/origin-metrics#4]
According to docs https://github.com/openshift/origin-metrics/blob/master/README.md , tried it against AWS instance devenv_fedora_2444.

[chunchen@F17-CCY daily]$ oc get po
NAME                         READY     STATUS    RESTARTS   AGE
hawkular-cassandra-1-omjzh   1/1       Running   0          17m
hawkular-metrics-7ovec       1/1       Running   0          17m
heapster-8w0l6               1/1       Running   1          17m

[chunchen@F17-CCY origin-metrics]$ oc logs hawkular-metrics-7ovec
<----------------------------------------------------snip------------------------------------------------------>
05:07:39,615 INFO  [org.jboss.weld.deployer] (MSC service thread 1-4) JBAS016002: Processing weld deployment hawkular-metrics-api-jaxrs.war
05:07:39,724 INFO  [org.jboss.weld.deployer] (MSC service thread 1-3) JBAS016005: Starting Services for CDI deployment: hawkular-metrics-api-jaxrs.war
05:07:39,790 INFO  [org.jboss.weld.Version] (MSC service thread 1-3) WELD-000900 1.1.29 (redhat)
05:07:39,816 INFO  [org.jboss.weld.deployer] (MSC service thread 1-4) JBAS016008: Starting weld service for deployment hawkular-metrics-api-jaxrs.war
05:07:41,189 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200002: Initializing metrics service
05:07:41,260 INFO  [org.jboss.web] (ServerService Thread Pool -- 50) JBAS018210: Register web context: /hawkular/metrics
05:07:41,645 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 28) JBAS015859: Deployed "hawkular-metrics-api-jaxrs.war" (runtime-name : "hawkular-metrics-api-jaxrs.war")
05:07:41,647 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 28) JBAS015859: Deployed "activemq-rar.rar" (runtime-name : "activemq-rar.rar")
05:07:41,747 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://127.0.0.1:9990/management
05:07:41,752 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:9990
05:07:41,752 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss EAP 6.4.1.GA (AS 7.5.1.Final-redhat-3) started in 9927ms - Started 267 of 303 services (62 services are lazy, passive or on-demand)
05:07:41,826 INFO  [com.datastax.driver.core.NettyUtil] (metricsservice-lifecycle-thread) Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
05:07:41,943 INFO  [org.jboss.resteasy.cdi.i18n] (http-/0.0.0.0:8080-1) RESTEASY006050: Found BeanManager at java:comp/BeanManager
05:07:42,188 INFO  [org.hibernate.validator.internal.util.Version] (http-/0.0.0.0:8080-1) HV000001: Hibernate Validator 4.3.2.Final-redhat-2
05:07:42,421 WARN  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200003: Could not connect to Cassandra cluster - assuming its not up yet: All host(s) tried for query failed (tried: hawkular-cassandra/172.30.252.165:9042 (com.datastax.driver.core.TransportException: [hawkular-cassandra/172.30.252.165:9042] Channel has been closed))
05:07:42,418 WARN  [io.netty.util.concurrent.DefaultPromise] (cluster1-nio-worker-0) An exception was thrown by com.datastax.driver.core.Connection$9.operationComplete(): java.util.concurrent.RejectedExecutionException: Task com.datastax.driver.core.Connection$9$1@48557a04 rejected from java.util.concurrent.ThreadPoolExecutor@706d85fa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) [rt.jar:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [rt.jar:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) [rt.jar:1.8.0_45]
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484) [guava-16.0.1.jar:]
	at com.datastax.driver.core.Connection$9.operationComplete(Connection.java:566) [cassandra-driver-core-2.2.0-rc2.jar:]
	at com.datastax.driver.core.Connection$9.operationComplete(Connection.java:542) [cassandra-driver-core-2.2.0-rc2.jar:]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:252) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:112) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1256) [netty-handler-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:676) [netty-handler-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:223) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:829) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:610) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
<----------------------------------------------------snip------------------------------------------------------>
05:08:18,906 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200002: Initializing metrics service
05:08:27,668 INFO  [com.datastax.driver.core.policies.DCAwareRoundRobinPolicy] (metricsservice-lifecycle-thread) Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
05:08:27,669 INFO  [com.datastax.driver.core.Cluster] (metricsservice-lifecycle-thread) New Cassandra host hawkular-cassandra/172.30.252.165:9042 added
05:08:27,851 INFO  [org.hawkular.metrics.schema.SchemaManager] (metricsservice-lifecycle-thread) HAWKMETRICS300002: Creating schema for keyspace hawkular_metrics
05:08:36,623 INFO  [org.hawkular.metrics.core.impl.MetricsServiceImpl] (metricsservice-lifecycle-thread) HAWKMETRICS100001: Using a key space of 'hawkular_metrics'
05:08:36,915 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200005: Metrics service started

Can anyone help to have a look?
Thanks!

**Comment by mwringe** [comment]
Oh, sorry, I somehow missed that an issue was created for this.

The good news is that your system seems to have started up properly: "Metrics service started".

Hawkular Metrics uses Cassandra as its metrics storage, and as such cannot do much if it can't connect to Cassandra. The reason you are seeing "Could not connect to Cassandra cluster" is that Cassandra is not yet fully running and Hawkular Metrics cannot establish a connection yet. It will continue polling until Cassandra becomes available, and once it is, you will see 'Metrics service started' in the logs.

The java.util.concurrent.RejectedExecutionException is an issue which can occur when Hawkular Metrics tries to connect to Cassandra before its ready. It's benign and you can safely ignore it.

The issue is being tracked in both the Hawkular Metrics project (https://issues.jboss.org/browse/HWKMETRICS-275) as well as with the Cassandra java driver (https://datastax-oss.atlassian.net/browse/JAVA-914).

I will create a known issue page to mention this issue so that it can help others avoid any confusion.

In the future, instead of posting logs into the issue, could you please create a gist for them instead and then add a link to the gist in the issue? If you post it in the issue itself its not always readable.

**Comment by chunyunchen** [comment]
@mwringe  Thanks for your help, will try again after the related issues are fixed.

**Comment by mwringe** [comment]
@chunyunchen The issue here is just an warning message that is showing up in the logs (which can be safely ignored).

From the message "Metrics service started" is should mean that the Hawkular Metrics pods has started up properly.

If you are running into any issues with things not working, please open another issue so that we can help you resolve it.
