### ISSUE TITLE
Hawkular-metrics pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by jjbeber** [openshift/origin-metrics#412]
I'm using a openshift v3.6.1 cluster and when I'm trying to enable cluster metrics the hawkular-metrics pod keeps in the state of CrashLoopBackOff.

I'm using the openshift/openshift-ansible repo with the branch `release-3.6`.

The message error in the pod:

```
2018-04-25 17:12:53,880 ERROR [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0362: Capabilities required by resource '/subsystem=infinispan/cache-container=ejb' are not available:
    org.wildfly.clustering.infinispan.cache-configuration.ejb.repl; Possible registration points for this capability: 
		/subsystem=infinispan/cache-container=*/local-cache=*
		/subsystem=infinispan/cache-container=*/invalidation-cache=*
		/subsystem=infinispan/cache-container=*/replicated-cache=*
		/subsystem=infinispan/cache-container=*/distributed-cache=*
2018-04-25 17:12:53,883 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
2018-04-25 17:12:53,894 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: WildFly Full 11.0.0.Final (WildFly Core 3.0.8.Final) stopped in 6ms
```
I'm not setting the version of metrics, so, it's the `origin-metrics-hawkular-metrics:latest`. 

That's the ansible command:
```
ansible-playbook -i hosts.yaml openshift-ansbile/playbooks/openshift-metrics/config.yml \
   -e openshift_metrics_install_metrics=True \
   -e openshift_metrics_hawkular_hostname=hawkular-metrics.apps.mycompany.com \
   -e openshift_metrics_cassandra_storage_type=pv
``` 

`hosts.yaml` has this relevant information:

```
openshift_metrics_install_metrics=true
openshift_metrics_cassandra_storage_type=dynamic
```

I know that's important to set the version, and I'm setting this to version v3.6.1 and it works, I'm relating this issue because it should be an image bug int the `lastest` version.

**Comment by jsanda** [comment]
I tested with latest and get different error with the same result - CrashLoopBackOff. 

```
  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Djava.awt.headless=true -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xbootclasspath/p:/opt/jboss/wildfly/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.0.4.Final.jar -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.PollSelectorProvider  -Xbootclasspath/p:/opt/jboss/wildfly/bin/alpn-boot-8.1.7.v20160121.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump
=========================================================================
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:183)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:397)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.util.logging.LogManager$1.run(LogManager.java:195)
	at java.util.logging.LogManager$1.run(LogManager.java:181)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at org.jboss.modules.Main.main(Main.java:485)
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.modules.Module.run(Module.java:332)
	at org.jboss.modules.Main.main(Main.java:525)
Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:183)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:397)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
```

I bumped the version of WildFly to 11.0.0, and I may have forgotten to update the version of the JBoss logging library.

**Comment by jsanda** [comment]
I fixed the logging error in a local branch, and now I get the infinispan configuration initially reported. When I upgraded WildFly, I made the mistake of only testing against EAP. I will get this sorted out. Thanks for reporting the issue.

**Comment by jjbeber** [comment]
You're welcome, glad for help :beers:

**Comment by jsanda** [comment]
This should be fixed when [PR 418](https://github.com/openshift/origin-metrics/pull/418) is merged.

**Comment by jjbeber** [comment]
The #418 is merged, closing this. Thanks, @jsanda
