### ISSUE TITLE
origin-metrics-cassandra does not run off the shelf

### ISSUE THREAD

**Issue by VolkerKozlowski** [openshift/origin-metrics#58]
Hi all,

running the docker image docker.io/openshift/origin-metrics-cassandra is facing into problems.

Any idea how to fix this issue to use origin-metrics-cassandra standalone?

Thanks, Volker

Errorlog:
```
sudo docker run -i -t openshift/origin-metrics-cassandra
[sudo] password for volker: 
CompilerOracle: inline org/apache/cassandra/db/AbstractNativeCell.compareTo (Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/db/composites/AbstractSimpleCellNameType.compareUnsigned (Lorg/apache/cassandra/db/composites/Composite;Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.selectBoundary (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;II)I
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.strictnessOfLessThan (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
INFO  16:38:19 Loading settings from file:/opt/apache-cassandra-2.2.1/conf/cassandra.yaml
INFO  16:38:19 Node configuration:[authenticator=AllowAllAuthenticator; authorizer=AllowAllAuthorizer; auto_snapshot=true; batch_size_warn_threshold_in_kb=5; batchlog_replay_throttle_in_kb=1024; cas_contention_timeout_in_ms=1000; client_encryption_options=<REDACTED>; cluster_name=hawkular-metrics; column_index_size_in_kb=64; commit_failure_policy=stop; commitlog_directory=/opt/apache-cassandra/data/commitlog; commitlog_segment_size_in_mb=32; commitlog_sync=periodic; commitlog_sync_period_in_ms=10000; compaction_throughput_mb_per_sec=16; concurrent_counter_writes=32; concurrent_reads=32; concurrent_writes=32; counter_cache_save_period=7200; counter_cache_size_in_mb=null; counter_write_request_timeout_in_ms=5000; cross_node_timeout=false; data_file_directories=[/opt/apache-cassandra/data/data]; disk_failure_policy=stop; dynamic_snitch_badness_threshold=0.1; dynamic_snitch_reset_interval_in_ms=600000; dynamic_snitch_update_interval_in_ms=100; endpoint_snitch=SimpleSnitch; hinted_handoff_enabled=true; hinted_handoff_throttle_in_kb=1024; incremental_backups=false; index_summary_capacity_in_mb=null; index_summary_resize_interval_in_minutes=60; inter_dc_tcp_nodelay=false; internode_compression=all; key_cache_save_period=14400; key_cache_size_in_mb=null; listen_address=fca9830b7e0d; max_hint_window_in_ms=10800000; max_hints_delivery_threads=2; memtable_allocation_type=heap_buffers; native_transport_port=9042; num_tokens=256; partitioner=org.apache.cassandra.dht.Murmur3Partitioner; permissions_validity_in_ms=2000; range_request_timeout_in_ms=10000; read_request_timeout_in_ms=5000; request_scheduler=org.apache.cassandra.scheduler.NoScheduler; request_timeout_in_ms=10000; row_cache_save_period=0; row_cache_size_in_mb=0; rpc_address=fca9830b7e0d; rpc_keepalive=true; rpc_port=9160; rpc_server_type=sync; seed_provider=[{class_name=org.hawkular.openshift.cassandra.OpenshiftSeedProvider, parameters=[{seeds=fca9830b7e0d}]}]; server_encryption_options=<REDACTED>; snapshot_before_compaction=false; ssl_storage_port=7001; sstable_preemptive_open_interval_in_mb=50; start_native_transport=true; start_rpc=true; storage_port=7000; thrift_framed_transport_size_in_mb=15; tombstone_failure_threshold=100000; tombstone_warn_threshold=1000; trickle_fsync=false; trickle_fsync_interval_in_kb=10240; truncate_request_timeout_in_ms=60000; write_request_timeout_in_ms=2000]
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Invalid yaml: file:/opt/apache-cassandra-2.2.1/conf/cassandra.yaml
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml: file:/opt/apache-cassandra-2.2.1/conf/cassandra.yaml
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:120)
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:85)
	at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:127)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:111)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:483)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:595)
Caused by: Can't construct a java object for tag:yaml.org,2002:org.apache.cassandra.config.Config; exception=Cannot create property=server_encryption_options for JavaBean=org.apache.cassandra.config.Config@4f83df68; Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
 in 'reader', line 10, column 1:
    cluster_name: 'hawkular-metrics'
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:475)
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:113)
	... 5 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=server_encryption_options for JavaBean=org.apache.cassandra.config.Config@4f83df68; Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	... 11 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
	... 13 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.constructStandardJavaInstance(Constructor.java:477)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:365)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
	... 16 more
ERROR 16:38:19 Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml: file:/opt/apache-cassandra-2.2.1/conf/cassandra.yaml
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:120) ~[apache-cassandra-2.2.1.jar:2.2.1]
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:85) ~[apache-cassandra-2.2.1.jar:2.2.1]
	at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:127) ~[apache-cassandra-2.2.1.jar:2.2.1]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:111) ~[apache-cassandra-2.2.1.jar:2.2.1]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:483) [apache-cassandra-2.2.1.jar:2.2.1]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:595) [apache-cassandra-2.2.1.jar:2.2.1]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: null; Can't construct a java object for tag:yaml.org,2002:org.apache.cassandra.config.Config; exception=Cannot create property=server_encryption_options for JavaBean=org.apache.cassandra.config.Config@4f83df68; Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption;  in 'reader', line 10, column 1:
    cluster_name: 'hawkular-metrics'
    ^
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:475) ~[snakeyaml-1.11.jar:na]
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:113) ~[apache-cassandra-2.2.1.jar:2.2.1]
	... 5 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=server_encryption_options for JavaBean=org.apache.cassandra.config.Config@4f83df68; Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331) ~[snakeyaml-1.11.jar:na]
	... 11 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=internode_encryption for JavaBean=org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions@55183b20; Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296) ~[snakeyaml-1.11.jar:na]
	... 13 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find enum value '/none' for enum class: org.apache.cassandra.config.EncryptionOptions$ServerEncryptionOptions$InternodeEncryption
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.constructStandardJavaInstance(Constructor.java:477) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:365) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296) ~[snakeyaml-1.11.jar:na]
	... 16 common frames omitted
[volker@ose cassandra-hawkular]$ sudo docker run -i -t openshift/origin-metrics-cassandra
```

**Comment by mwringe** [comment]
We don't currently have a standalone option for our Cassandra images, they are meant to be run as part of the Origin Metrics components, and run within an OpenShift environment and not directly via docker.

It looks like we have a typo here which is causing the problem https://github.com/openshift/origin-metrics/blob/master/cassandra/cassandra-docker.sh#L170

We will need to update that script and write a test to make sure that the Cassandra image can be directly started.

**Comment by VolkerKozlowski** [comment]
Thanks. We'd like to use it standalone in Openshift environment as a scalable cassandra. Please let me know if it is possible with this image.

To get it up with docker I temporarily fixed cassandra-docker.sh and replaced the SeedProvider.

**Comment by mwringe** [comment]
I have a PR which will fix the typo from preventing a standalone Cassandra image from being started, but this will not give you a scaleable Cassandra on its own.

The Cassandra image in origin-metrics is configured to be used with the provided Hawkular Metrics instance and we don't have a fully standalone option at the moment. Even with the current setup it is requires some manual steps in order to scale the Cassandra instance (see https://github.com/openshift/origin-metrics/blob/master/docs/cassandra_scaling.adoc) 

When petsets (https://github.com/kubernetes/kubernetes/pull/18016) are available, then the scaling solution should be much smoother.

**Comment by jcantrill** [comment]
@mwringe I presume we should close this issue since it is not our intention for the metrics cassandra image to run stand alone.  The user should defer to cassandra's stock image?

**Comment by mwringe** [comment]
@jcantrill Agreed, the docker image can now also run standalone but in a limited fashion. Closing this issue.
